// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ecpbxiuyicclimgljbwx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjcGJ4aXV5aWNjbGltZ2xqYnd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MDk5NTgsImV4cCI6MjA3MDA4NTk1OH0.UHPuR1po0sWQKClnOXdl4u5I1xu2d_rrQQDq_QVfB7k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});